[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "drag_and_drop",
    "indexeddb",
    "localstorage",
    "scroll"
]
