name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: circleci/python:latest-browsers

    steps:
      - name: Provide access to working directory
        run: sudo chown -R $USER:$USER /home/github/actions-runner/_work/selenium-tools

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
