name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      containerUser: ${{ steps.get-user.outputs.containerUser }}
    
    steps:
      - id: get-user
        run: echo "::set-output name=containerUser::`id -u`:`id -g`"

  test:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: circleci/python:latest-browsers
      options: --user ${{ needs.configure.outputs.containerUser }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
