name: Quality Control

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run format verifications
        run: python -m black --check --verbose .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chrome browser
        run: apt-get install -y --no-install-recommends google-chrome-stable
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest
